name: Sync Staging Master to Prod

on:
  push:
    branches:
      - develop

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout staging repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "user-docs-bot"
          git config --global user.email "bot@clevertap.com"

      - name: Add prod repo remote
        run: |
          git remote add prod https://x-access-token:${{ secrets.PROD_PAT }}@github.com/CleverTap/Prod-User-Docs.git

      - name: Push to prod master
        run: |
          git push prod master --force
